spring.application.name=tekbook
server.port=8080

# Actuator : health est expose par defaut, on ajoute le detail pour le Lab 3
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
